#! /usr/bin/python
# -*- coding: utf-8 -*-
# vi: sts=4 et sw=4

import sys
sys.path = ['./modules/'] + sys.path
from bitcoim.db import SQL, Database
from bitcoin.controller import Controller
from common import problem, debug
from conf import bitcoin as bitcoinConf, db
try:
    from conf import component as info
except ImportError:
    problem("Error: Please create a file named 'conf.py' (e.g. rename and edit conf.py.example).", True)
try:
    from xmpp import client, protocol
except ImportError:
    problem("Error: this program needs the Python XMPP library.", True)
from bitcoim.component import Component

reload(sys)
sys.setdefaultencoding('utf8')
SQL(url=db['file'])
database = Database(db['file'])
database.upgrade(1)
try:
    Controller(bitcoinConf['user'], bitcoinConf['password']).getinfo()
except IOError:
    problem("Communication error with bitcoin client", True)
try:
    bitcoIM = Component(info['jid'], info['password'], info['server'], info['port'])
except Exception, message:
    problem("Error while connecting to server: %s" % (message), True)
try:
    bitcoIM.loop(10)
except KeyboardInterrupt:
    bitcoIM.sayGoodbye()
